# -*- coding: utf-8 -*-

QUOTE_STATUSES = [
    "DRAFT",
    "SENT",
    "REVISED",
    "CUSTOMER_APPROVED",
    "REJECTED",
    "EXPIRED",
    "CONVERTED",
]

ORDER_STATUSES = [
    "DRAFT",
    "APPROVED",
    "PICKING",
    "PART_SHIPPED",
    "SHIPPED",
    "PART_INVOICED",
    "INVOICED",
    "CANCELED",
]

ROLE_SALES = "SALES"
ROLE_SALES_MANAGER = "SALES_MANAGER"
ROLE_FINANCE = "FINANCE"
ROLE_ADMIN = "ADMIN"
ROLE_VIEWER = "VIEWER"

CONVERT_ROLES = {ROLE_SALES, ROLE_SALES_MANAGER, ROLE_FINANCE, ROLE_ADMIN}
